### ISSUE TITLE
create_access_token returns None

### ISSUE THREAD

**Issue by long-settlement** [PropelAuth/propelauth-py#11]
Following [this documentation](https://docs.propelauth.com/reference/backend-apis/python) I notice that `create_access_token` returns `None` (or raises an exception) but never returns an actual token as the docs suggest it should.

As far as I can see, the underlying _create_access_token method doesn't even attempt to return the value.  Is this as expected?

**Comment by andrew-propelauth** [comment]
Sorry about that - that was a bug. Really appreciate the fix! v3.1.2 was just released which includes your fix.
